@startuml Activity Diagram
title Server
start
partition Constructor {
    :Set TCP IP;
    :Set TCP Port;
    :Set Buffer Size;
    :Create Socket;
}
partition RunServer {
    :Bind;
    :Listen;
    repeat
        :Receive Connection;
        :Receive Data;
        switch (action)
        case (withdraw) 
            :Validate Withdrawal;
            :Send Response;
        case (deposit) 
            :Process Deposit;
            :Send Response;
        endswitch
    repeat while(true)
    stop
}
end
@enduml