@startuml ValidateWithdrawal 
title Server
start
if (is new client?) then (yes)
    :Send "Make a deposit first" message;
    stop
endif
*Calculate balance from blockchain;
** Find all blocks owned by ownerName and sum their values;
if (balance >= amount?) then (yes)
    :Approve withdrawal;
    :Create new Block;
    :Add Block to blockchain;
    :Send "Withdrawal approved" message;
else (no)
    :Send "Insufficient balance" message; 
end
@enduml