@startuml Activity Diagram
title Client
start
partition Constructor {
    :Set name;
    :Set Buffer Size;
    :Create Socket;
    :Set balance to 0;
}
partition RunClient {
    :Connect to Server (given server IP and port);
    :Deposit money;
    repeat
        switch (action)
            case (withdraw) 
                :Request withdrawal from Server;
            case (deposit) 
                :Request deposit to Server;
        endswitch
        :Receive Message;
        :Print Message;
        :Wait for next action;
    repeat while(action != close) is (true) not (false)
}
end
@enduml