@startuml class_diagram 
skinparam classAttributeIconSize 0

class Block {
  #balance: float {readonly}
  #hash: String {readonly}
}

class GenesisBlock {
  -ownerName: String {readonly}
  -creationTime: Time {readonly}
}

Block <|-- GenesisBlock


abstract class NetworkNode
{
  -socket: Socket {readonly}
  -ip: String {readonly}
  -port: String {readonly}
}

class Client {
  -name: String {readonly}
  -balance: float
  -deposit(amount: float)
  -withdraw(amount: float)
}

class Server {
  -deposit(amount: float)
  -withdraw(amount: float)
  -calculateHash(block: Block): String
' A validação só é feita pelo servidor
  -validateWithdrawal(amount: float, ownerName: float)
}

NetworkNode <|-- Client
NetworkNode <|-- Server

' BlockChain
Server *--> "many" Block

' O Server tem um atributo que mapeia por string os clientes map(String) = Cliente
Server "1"--"many" Client 
@enduml