@startuml class_diagram 
skinparam classAttributeIconSize 0
hide circle
skinparam Shadowing false

class Block {
  #balance: float {readonly}
  #hash: String {readonly}
}

class GenesisBlock {
  -ownerName: String {readonly}
  -creationTime: Time {readonly}
}

Block <|-- GenesisBlock


abstract class NetworkNode <<abstract>>
{
  -socket: Socket {readonly}
  -bufferSize: unsigned int {readonly}
  -ip: String {readonly}
  -port: String {readonly}
  -getOwnIP(): String
}

class Client {
  -name: String {readonly}
  -balance: float
  -deposit(amount: float)
  -withdraw(amount: float)
}

class Server {
  ' A segunda string é o nome do cliente
  -clients: map(String, String) {readonly}
  -deposit(amount: float)
  -withdraw(amount: float)
  -calculateHash(block: Block): String
' A validação só é feita pelo servidor
  -validateWithdrawal(amount: float, ownerName: float)
  -getBalance(clientName: String): float
}

NetworkNode <|-- Client
NetworkNode <|-- Server

' BlockChain
Server *--> "many" Block

' O Server tem um atributo que mapeia por string os clientes map(String) = NomeCliente
Server "1"--"many" Client 
@enduml